name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./gosberpay.go

    - name: Build
      run: go build -v ./mtls-grpc-gateway/gw-mtls-gate/reverse-proxy-server.go
      
    - name: Test
      run: go test -v ./mtls-grpc-gateway/gw-mtls-gate/reverse-proxy-server-unit_test.go

   - name: Build
      run: go build -v ./mtls-grpc-gateway/gw-mtls-service/grpc-service.go
      
    - name: Test
      run: go test -v ./mtls-grpc-gateway/gw-mtls-service/service-logic-unit_test.go